### ISSUE TITLE
DocPad boilerplate/option?

### ISSUE THREAD

**Issue by balupton** [addyosmani/backbone-boilerplates#1]
Perhaps you could create another option for [DocPad](http://github.com/balupton/docpad)? Here is a backbone.js app already using it [Node Chat](https://github.com/balupton/nodechat.docpad)

Would love to know your thoughts!?

**Comment by addyosmani** [comment]
@balupton Thanks. I've taken a look through the summary notes in your README. Correct me if I'm wrong, but the problem DocPad tries to solve is providing scaffolding and site generation based on multiple template files? (any help you can provide in explaining what it does would be great)
